<!DOCTYPE html>
<html class="no-js">
    <head>
        <title>Church manager</title>		   
        <!-- Bootstrap -->
		
			<link href="../public/images/logo7.png" rel="icon" type="image">
			<link href="../public/bootstrap/css/print_background.css" rel="stylesheet" media="screen">
			<link href="../public/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
			<link href="../public/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" media="screen">
			<link href="../public/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
			<link href="../public/bootstrap/css/font-awesome.css" rel="stylesheet" media="screen">
			<link href="../public/bootstrap/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
			<link href="../public/bootstrap/css/my_style.css" rel="stylesheet" media="screen">
			<link href="../public/assets/styles.css" rel="stylesheet" media="screen">	
			<link href="../public/bootstrap/css/print_inventory.css" rel="stylesheet" media="print">						
		    <link href="../public/bootstrap/css/bootstrap.min1.css" rel="stylesheet" media="screen">
		  
        <!-- HTmL5 shim, for IE6-8 support of HTmL5 elements -->
        <!--[if lt IE 9]>
          
        <![endif]-->
		<!-- calendar css -->
		<script src="../public/bootstrap/js/html5.js"></script>
		<link href="../public/vendors/fullcalendar/fullcalendar.css" rel="stylesheet" media="screen">
		<script src="../public/vendors/jquery-1.9.1.min.js"></script>
        <script src="../public/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
		<!-- data table -->
		<link href="../public/assets/DT_bootstrap.css" rel="stylesheet" media="screen">
		<!-- notification  -->
		<link href="../public/vendors/jGrowl/jquery.jgrowl.css" rel="stylesheet" media="screen">
		<!-- wysiwug  -->
		<link rel="stylesheet" type="text/css" href="../public/vendors/bootstrap-wysihtml5/src/bootstrap-wysihtml5.css"></link>
	
		<script src="../public/vendors/jGrowl/jquery.jgrowl.js"></script>
    </head>
<?php include('../lib/dbcon.php'); 
dbcon(); 
?>